#!/usr/bin/env python

import glob
import os
import os.path
import shutil
import subprocess
import tempfile

def run_test(d):
    curdir = os.getcwd()
    tmpdir = tempfile.mkdtemp()
    target_dir = os.path.join(tmpdir, os.path.basename(d))
    shutil.copytree(d, target_dir)
    try:
        os.chdir(target_dir)
        p = subprocess.check_output(["python", "test.py"])
        print p
    finally:
        os.chdir(curdir)
        shutil.rmtree(tmpdir)
        

def main():
    tests = glob.glob("tests/*")
    for test in tests:
        run_test(test)

main()
